[package]
edition = "2021"
name = "ssd1306-async-examples"
version = "0.1.0"

[dependencies]
cortex-m = { version = "0.7.6", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.0"
defmt = "1.0.1"
defmt-rtt = "1.0.0"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }

embassy-executor = { version = "0.9.0", features = ["arch-cortex-m", "executor-thread", "executor-interrupt", "defmt"] }
embassy-time = { version = "0.5.0", features = ["defmt", "defmt-timestamp-uptime"] }
embassy-futures = { version = "0.1" }
embassy-sync = { version = "0.7.2", features = ["defmt"] }
embassy-rp = { version = "0.8.0", features = ["defmt", "unstable-pac", "time-driver", "rp2040"] }
embassy-embedded-hal = { version = "0.5.0", features = ["defmt"] }
embedded-hal-bus = { version = "0.3.0", features = ["async"] }


static_cell = { version = "2.1.0", features = []}
portable-atomic = { version = "1.6", features = ["critical-section"] }


ssd1306-async = { path = "../" }
tinybmp = "0.6.0"
embedded-graphics = "0.8.1"
embedded-hal-async = "=1.0.0"

[patch.crates-io]
embassy-executor = { git = "https://github.com/embassy-rs/embassy", rev = "f86cf87f2f20f723e2ba2fe7d83908a2b3bac2d1" }
embassy-time = { git = "https://github.com/embassy-rs/embassy", rev = "f86cf87f2f20f723e2ba2fe7d83908a2b3bac2d1" }
embassy-futures = { git = "https://github.com/embassy-rs/embassy", rev = "f86cf87f2f20f723e2ba2fe7d83908a2b3bac2d1" }
embassy-sync = { git = "https://github.com/embassy-rs/embassy", rev = "f86cf87f2f20f723e2ba2fe7d83908a2b3bac2d1" }
embassy-rp = { git = "https://github.com/embassy-rs/embassy", rev = "f86cf87f2f20f723e2ba2fe7d83908a2b3bac2d1" }
embassy-embedded-hal = { git = "https://github.com/embassy-rs/embassy", rev = "f86cf87f2f20f723e2ba2fe7d83908a2b3bac2d1" }

[profile.release]
debug = true
